package com.roderus.app.listviewdemo;

public class NameArrays {

    public static String[] wvornamen = {
            "Emma",
            "Mia",
            "Hannah / Hanna",
            "Emilia",
            "Sofia / Sophia",
            "Lina",
            "Anna",
            "Mila",
            "Lea",
            "Ella",
            "Clara / Klara",
            "Marie",
            "Lena",
            "Luisa / Louisa",
            "Leni",
            "Leonie",
            "Johanna",
            "Emily / Emilie",
            "Mathilda / Matilda",
            "Amelie",
            "Frieda / Frida",
            "Charlotte",
            "Lia / Liah / Lya",
            "Sophie / Sofie",
            "Ida",
            "Lilly / Lilli",
            "Maja / Maya",
            "Greta",
            "Lara",
            "Laura",
            "Nele / Neele",
            "Lotta",
            "Sarah / Sara",
            "Melina",
            "Mira",
            "Nora",
            "Pia",
            "Elisa",
            "Paula",
            "Victoria / Viktoria",
            "Julia",
            "Marlene",
            "Lisa",
            "Juna / Yuna",
            "Alina",
            "Pauline",
            "Isabella",
            "Maria",
            "Elena",
            "Helena",
            "Mara / Marah",
            "Luise / Louise",
            "Anni",
            "Luna",
            "Antonia",
            "Tilda",
            "Finja / Finnja",
            "Thea",
            "Romy",
            "Theresa / Teresa",
            "Isabell / Isabel / Isabelle",
            "Merle",
            "Emely / Emelie",
            "Elina",
            "Fiona",
            "Paulina",
            "Eva",
            "Rosalie",
            "Jana",
            "Katharina",
            "Josephine/ Josefine",
            "Zoe / Zoé",
            "Malia",
            "Magdalena",
            "Lucy / Lucie",
            "Mina",
            "Elli / Elly",
            "Amy",
            "Hailey",
            "Jule",
            "Maila / Mayla",
            "Carla / Karla",
            "Stella",
            "Martha / Marta",
            "Annika",
            "Carlotta / Karlotta",
            "Milena",
            "Elisabeth",
            "Lotte",
            "Ronja",
            "Nina",
            "Valentina",
            "Jasmin / Yasmin",
            "Amalia",
            "Annabell / Annabelle",
            "Chiara / Kiara",
            "Linda",
            "Luana",
            "Melissa",
            "Olivia",
            "Emmi / Emmy",
            "Amelia",
            "Miriam",
            "Aaliyah / Aliya",
            "Liana",
            "Alma",
            "Elif",
            "Franziska",
            "Zoey",
            "Alessia",
            "Anastasia",
            "Leila / Leyla",
            "Aurelia",
            "Helene",
            "Freya",
            "Kira / Kyra",
            "Marla",
            "Ela",
            "Malina",
            "Diana",
            "Selina",
            "Lenja / Lenya",
            "Tessa",
            "Jette",
            "Liya",
            "Milla",
            "Aylin / Eileen / Aileen / Ayleen",
            "Lene",
            "Mariella",
            "Rosa",
            "Lynn / Linn",
            "Vanessa",
            "Amira",
            "Ylvi / Ylvie",
            "Liv",
            "Lucia",
            "Sina / Sinah",
            "Carolin / Caroline / Karoline",
            "Alexandra",
            "Liliana",
            "Ava",
            "Aria / Arya",
            "Enna",
            "Rebecca",
            "Alea",
            "Lana",
            "Milana",
            "Marleen / Marlen",
            "Samira",
            "Alisa",
            "Evelyn / Evelin / Eveline",
            "Livia",
            "Aurora",
            "Alicia",
            "Amina",
            "Ariana",
            "Alice",
            "Edda",
            "Laila / Layla",
            "Larissa",
            "Melia",
            "Bella",
            "Leana",
            "Lenia",
            "Mona",
            "Daria",
            "Elsa",
            "Leticia / Letizia",
            "Talia / Thalia",
            "Julie",
            "Giulia",
            "Nela",
            "Alissa / Alyssa",
            "Amilia",
            "Medina",
            "Carolina / Karolina",
            "Jolina / Joelina",
            "Tabea",
            "Annalena",
            "Elise",
            "Veronika",
            "Heidi",
            "Mathea / Matea",
            "Hedi / Hedy",
            "Vivien / Vivienne",
            "Christina",
            "Jonna",
            "Lorena",
            "Jara / Yara",
            "Miray",
            "Sena",
            "Maira / Meyra",
            "Nika",
            "Ina",
            "Linea / Linnea",
            "Cataleya",
            "Zeynep",
            "Smilla",
            "Selma",
            "Celina",
            "Natalie / Nathalie",
            "Valerie",
            "Fenja",
            "Celine",
            "Felicitas",
            "Levke",
            "Svea",
            "Eliana",
            "Meryem",
            "Kaja / Kaya / Caja",
            "Tamara",
            "Hermine",
            "Liara",
            "Marina",
            "Aleyna",
            "Annelie",
            "Fabienne",
            "Mariam / Maryam",
            "Ayla",
            "Helen",
            "Hira",
            "Noemi",
            "Malea",
            "Malou",
            "Joleen",
            "Rieke",
            "Alena",
            "Angelina",
            "Malin",
            "Marlena",
            "Nisa",
            "Elin",
            "Hilda",
            "Carina / Karina",
            "Elea",
            "Flora",
            "Henriette",
            "Nala / Nahla",
            "Clea",
            "Dana",
            "Nelly / Nelli",
            "Ruby",
            "Azra",
            "Florentine",
            "Josie / Josy",
            "Madita",
            "Melody",
            "Naila / Nayla",
            "Xenia",
            "Kate",
            "Mailin / Maylin",
            "Estelle",
            "Jella",
            "Leona",
            "Lou",
            "Valeria",
            "Felina",
            "Holly",
            "Melek",
            "Palina",
            "Dilara",
            "Alia",
            "Alya",
            "Eleni",
            "Enya",
            "Arina",
            "Defne",
            "Tara",
            "Fine / Fiene",
            "Michelle",
            "Adriana",
            "Asya",
            "Leia / Leya",
            "Alva",
            "Anne",
            "Melisa",
            "Tamina",
            "Juliana",
            "Sonja",
            "Enie",
            "Joline / Joeline",
            "Käthe",
            "Leandra",
            "Liesbeth / Lisbeth",
            "Lieselotte",
            "Selin",
            "Adelina",
            "Esila",
            "Nicole",
            "Fatima",
            "Leonora",
            "Hedda",
            "Josefin / Josephin",
            "Kim",
            "Naomi",
            "Ada",
            "Evelina",
            "Grace",
            "Kimberly / Kimberley",
            "Lilith",
            "Delia",
            "Esther",
            "Lilia",
            "Liz",
            "Mary",
            "Amanda",
            "Cleo",
            "Ellen",
            "Joana / Joanna",
            "Samantha",
            "Viola",
            "Wilma",
            "Cara",
            "Eda",
            "Lilian / Lillian",
            "Liyana",
            "Lydia",
            "Talea",
            "Tiana",
            "Cecilia",
            "Claire",
            "Fritzi",
            "Jessika / Jessica",
            "Lola",
            "Madlen / Madleen",
            "Melanie",
            "Melinda",
            "Philippa",
            "Eleonora",
            "Esma",
            "Iva",
            "Minna",
            "Tuana",
            "Amaya",
            "Janne",
            "Zehra",
            "Anouk",
            "Dalia",
            "Jolie",
            "Kiana",
            "Miley",
            "Nila",
            "Hazal",
            "Adele",
            "Eliza",
            "Ilayda",
            "Jolien",
            "Madeleine",
            "Nike",
            "Stina",
            "Eleanor",
            "Maike / Meike",
            "Nia",
            "Penelope",
            "Verena",
            "Zümra",
            "Annemarie",
            "Ivy",
            "Malena",
            "Neyla",
            "Runa",
            "Amara",
            "Anisa",
            "Charlotta",
            "Felia",
            "Jenna",
            "Philine",
            "Tina",
            "Abigail",
            "Anja",
            "Ashley",
            "Hilal",
            "Mika",
            "Nadia",
            "Skadi",
            "Enni / Enny",
            "Friederike",
            "Lisann / Lysann",
            "Liva",
            "Ria",
            "Stefanie / Stephanie",
            "Chloe",
            "Helin",
            "Jasmina",
            "Josephina / Josefina",
            "Juliane",
            "Maileen / Mayleen",
            "Mathilde",
            "Patricia",
            "Salome",
            "Vera",
            "Elenor",
            "Jill / Jil",
            "Meta",
            "Natalia",
            "Romina",
            "Selena",
            "Sila",
            "Soraya",
            "Sunny",
            "Alexia",
            "Alica",
            "Bianca / Bianka",
            "Dorothea",
            "Eylül",
            "Felicia",
            "Feline",
            "Gerda",
            "Isa",
            "Janina",
            "Marieke / Marike",
            "Nelia",
            "Sandra",
            "Alara",
            "Alexa",
            "Amine",
            "Elaine",
            "Toni / Tony",
            "Annabella",
            "Clarissa",
            "Ece",
            "Janna",
            "Judith",
            "Lavin",
            "Saphira",
            "Svenja",
            "Yade",
            "Zuzanna",
            "Alba",
            "Ann",
            "Cora",
            "Ema",
            "Hanni",
            "Inga",
            "Josefa / Josepha",
            "Joy",
            "Nova",
            "Yaren",
            "Alisha",
            "Andrea",
            "Arin",
            "Charlie / Charly",
            "Elara",
            "Emilija",
            "Fina",
            "Franka",
            "Irma",
            "Katrin / Catrin / Kathrin",
            "Laya",
            "Lilou",
            "Line",
            "Marit",
            "Melis",
            "Noelia",
            "Nour",
            "Ophelia",
            "Saskia",
            "Zara",
            "Asel",
            "Beatrice",
            "Cheyenne / Chayenne",
            "Daniela",
            "Davina",
            "Elissa",
            "Erna",
            "Eslem",
            "Florentina",
            "Ines",
            "Lorin",
            "Maia",
            "Margarete",
            "Megan",
            "Michaela",
            "Tala",
            "Almira",
            "Amal",
            "Amila",
            "Cosima",
            "Enisa",
            "Ewa",
            "Gloria",
            "Maxi",
            "Rahel",
            "Yagmur",
            "Alana",
            "Belinay",
            "Gabriela",
            "Giuliana",
            "Henrieke / Henrike",
            "Ileyna",
            "Jona / Jonah",
            "Kaia",
            "Luzi / Luzie",
            "Madison",
            "Marisa",
            "Mieke",
            "Milina",
            "Naya",
            "Nefes",
            "Scarlett"
    };

    public static String[] mvornamen = {
            "Ben",
            "Paul",
            "Leon",
            "Finn / Fynn",
            "Elias",
            "Jonas",
            "Luis / Louis",
            "Noah",
            "Felix",
            "Lukas / Lucas",
            "Henry / Henri",
            "Luca / Luka",
            "Maximilian",
            "Emil",
            "Theo",
            "Matteo",
            "Oskar / Oscar",
            "Anton",
            "Jakob / Jacob",
            "Max",
            "Liam",
            "Moritz",
            "Leo",
            "David",
            "Alexander",
            "Milan",
            "Julian",
            "Niklas / Niclas",
            "Carl / Karl",
            "Philipp",
            "Tim",
            "Samuel",
            "Mats / Mads",
            "Tom",
            "Erik / Eric",
            "Linus",
            "Jonathan",
            "Mika",
            "Leonard",
            "Vincent",
            "Jona / Jonah",
            "Jan",
            "Hannes",
            "Rafael / Raphael",
            "Levi",
            "Fabian",
            "Aaron",
            "Jannik / Yannik / Yannick / Yannic",
            "Simon",
            "Jannis / Janis / Yannis",
            "Julius",
            "Johann",
            "Johannes",
            "Till",
            "Benjamin",
            "Adrian",
            "Joshua",
            "Lennard / Lennart",
            "Nico / Niko",
            "Valentin",
            "Maxim / Maksim",
            "Marlon",
            "Mattis / Mathis / Matthis",
            "Constantin / Konstantin",
            "Daniel",
            "Theodor",
            "Mohammed / Muhammad",
            "Luke / Luc",
            "Artur / Arthur",
            "Ole",
            "Lenny",
            "Lian",
            "Florian",
            "Kilian",
            "Pepe",
            "Nick",
            "Fiete",
            "Milo / Milow",
            "Nils / Niels",
            "Toni / Tony",
            "Lio",
            "Sebastian",
            "Benedikt",
            "Adam",
            "Malte",
            "Phil",
            "John",
            "Timo",
            "Damian",
            "Gabriel",
            "Bruno",
            "Lias",
            "Levin",
            "Tobias",
            "Lasse",
            "Emilio",
            "Fritz",
            "Michael",
            "Carlo",
            "Matti",
            "Dominic / Dominik",
            "Jannes",
            "Emilian",
            "Franz",
            "Noel",
            "Ludwig",
            "Leopold",
            "Lennox",
            "Oliver",
            "Joris",
            "Jayden / Jaden",
            "Frederik / Frederic",
            "Robin",
            "Joel",
            "Justus",
            "Alessio",
            "Malik",
            "Lars",
            "Nicolas / Nikolas",
            "Bennet",
            "Richard",
            "Sam",
            "Len / Lenn",
            "Christian",
            "Elia / Eliah",
            "Jonte",
            "Thilo / Tilo",
            "Colin / Collin",
            "Bastian",
            "Enno",
            "Friedrich",
            "Luan",
            "Marc / Mark",
            "Piet",
            "Ilias / Ilyas",
            "Michel",
            "Charlie / Charly",
            "Lion",
            "Neo",
            "Hugo",
            "Matthias",
            "Silas",
            "Emir",
            "Ali",
            "Jamie",
            "Benno",
            "Lorenz",
            "Josef / Joseph",
            "Thore",
            "Leandro",
            "Arian",
            "Tyler / Tayler",
            "Yusuf",
            "Kian",
            "Arne",
            "Jaron / Yaron",
            "Jason",
            "Bela",
            "Amir",
            "Dean",
            "Lionel",
            "Ferdinand",
            "Konrad",
            "Jasper",
            "Finnley / Finley / Finlay",
            "Willi / Willy",
            "Manuel",
            "Henrik",
            "Victor / Viktor",
            "Andreas",
            "Curt / Kurt",
            "Marcel",
            "Tristan",
            "Leano",
            "Mailo",
            "Marvin / Marwin",
            "Aiden / Ayden",
            "Eddie / Eddy",
            "Nathan",
            "Alex",
            "Gustav",
            "Connor / Conner",
            "Fabio",
            "Leonardo",
            "Thomas",
            "Yasin",
            "Elian",
            "Ömer",
            "Leonhard",
            "Aras",
            "Nikita",
            "Clemens / Klemens",
            "Dennis",
            "Hendrik",
            "Diego",
            "Samu",
            "Georg",
            "Marco / Marko",
            "Martin",
            "Ian",
            "Maik / Meik / Mike",
            "Lino",
            "Magnus",
            "Mio",
            "William",
            "Mert",
            "Brian / Bryan",
            "Hamza",
            "Xaver",
            "Eymen",
            "Janosch",
            "Lean",
            "Can",
            "Marten",
            "Tiago / Thiago",
            "Elija / Elijah",
            "Mick",
            "Patrick",
            "Albert",
            "Korbinian",
            "Leander",
            "Marius",
            "Nino",
            "Otto",
            "Edgar",
            "Bjarne",
            "Darian",
            "Antonio",
            "Wilhelm",
            "Henning",
            "Claas / Klaas",
            "Janne",
            "Kai / Kay",
            "Dario",
            "Titus",
            "Ahmet",
            "Christoph",
            "Ibrahim",
            "Gregor",
            "Robert",
            "Carlos",
            "Jack",
            "Roman",
            "Stefan / Stephan",
            "Markus / Marcus",
            "Timur",
            "Nevio",
            "Miran",
            "Enes",
            "Laurens / Laurenz",
            "Marlo",
            "Mustafa",
            "Bilal",
            "Jano",
            "Younes",
            "Hans",
            "Omar",
            "Alan",
            "Leonas",
            "Alessandro",
            "Deniz",
            "Kaan",
            "Jakub",
            "Laurin",
            "Sami",
            "Erwin",
            "Mehmet",
            "Torben / Thorben",
            "Armin",
            "Ayaz",
            "Darius",
            "Ilay",
            "Julien",
            "Peter",
            "Mikail",
            "Rayan",
            "Ruben",
            "Alwin",
            "James",
            "Milian",
            "Tammo",
            "Thies",
            "Yunus",
            "Hanno",
            "Mattes",
            "Ryan",
            "Josua",
            "Kjell",
            "Quirin",
            "Alfred",
            "Ensar",
            "Ivan",
            "Joscha",
            "Kevin",
            "Ragnar",
            "Jordan",
            "Kerem",
            "Maurice",
            "Mirac",
            "Valentino",
            "Ahmad",
            "Leonidas",
            "Youssef",
            "Umut",
            "Devin",
            "Emin",
            "Jaro",
            "Kalle",
            "Pascal",
            "Hassan / Hasan",
            "Jeremy",
            "Logan",
            "Pius",
            "Chris",
            "Danny / Denny",
            "Emanuel",
            "Taylor",
            "Thorin",
            "Dylan",
            "Junis",
            "Nelio",
            "Caspar",
            "Jonne",
            "Kenan",
            "Pablo",
            "Amin",
            "Giuliano",
            "Selim",
            "Timon",
            "Vitus",
            "Yigit",
            "Antoni / Antony",
            "Aurelio",
            "Egon",
            "Kiyan",
            "Leif",
            "Tino",
            "Mahir",
            "Nikolai",
            "Andre",
            "Berat",
            "Efe",
            "Joost / Jost",
            "Kuzey",
            "Edwin",
            "Emre",
            "Jerome",
            "Jon",
            "Louie",
            "Marian",
            "Ricardo / Riccardo",
            "Rudi",
            "Eduard",
            "Keno",
            "Lutz",
            "Marek",
            "Sascha",
            "Tamme",
            "Amar",
            "Azad",
            "Eren",
            "Loris",
            "Tjark",
            "Angelo",
            "Damien",
            "Fred",
            "Jarno",
            "Jim",
            "Johnny",
            "Karim",
            "Mario",
            "Romeo",
            "Tamino",
            "Atilla / Attila",
            "Bosse",
            "Cedric / Cedrik",
            "Christopher",
            "Hector / Hektor",
            "Miko",
            "Samir",
            "Sandro",
            "Francesco",
            "George",
            "Ilja",
            "Jamal",
            "Jesse",
            "Mattia",
            "Merlin",
            "Vito",
            "Levent",
            "Lucien",
            "Malek",
            "Taha",
            "Tillman / Tilman",
            "Adem",
            "August",
            "Björn",
            "Danilo",
            "Domenic / Domenik",
            "Eliano",
            "Semih",
            "Tommi",
            "Veit",
            "Arno",
            "Arvid",
            "Baran",
            "Dion",
            "Giuseppe",
            "Jari",
            "Jarne",
            "Leonid / Leonit",
            "Levian",
            "Adriano",
            "Alexandros",
            "Arik",
            "Aurel",
            "Dante",
            "Miro",
            "Quentin",
            "Sinan",
            "Abdullah",
            "Anas",
            "Ansgar",
            "Aryan",
            "Etienne",
            "Hauke",
            "Ismail",
            "Jake",
            "Juri",
            "Koray",
            "Kuno",
            "Matei",
            "Rune",
            "Said",
            "Falk",
            "Flynn",
            "Hüseyin",
            "Isa",
            "Nael",
            "Noar",
            "Yunis",
            "Amon",
            "Anthony",
            "Cem",
            "Enzo",
            "Fatih",
            "Heinrich",
            "Joe",
            "Lorenzo",
            "Musa",
            "Poyraz",
            "Taylan",
            "Benny",
            "Berkay",
            "Bo",
            "Enrico",
            "Lewis",
            "Miguel",
            "Nilas",
            "Salvatore",
            "Alois",
            "Casper / Kasper",
            "Cinar",
            "Damon",
            "Ege",
            "Eray",
            "Imran",
            "Issa",
            "Jackson",
            "Jean",
            "Kerim",
            "Lucian",
            "Mason",
            "Mino",
            "Peer",
            "Rocco",
            "Santiago",
            "Zayn",
            "Arda",
            "Ari",
            "Georgios",
            "Giovanni",
            "Halil",
            "Hussein",
            "Ioannis",
            "Kimi",
            "Mikael",
            "Nathanael",
            "Prince",
            "Severin",
            "Sven",
            "Taim",
            "Tizian",
            "Amadeus",
            "Artjom",
            "Christiano / Cristiano",
            "Dave",
            "Edin",
            "Jay",
            "Jimmy"};
}
